### ISSUE TITLE
[Feature Request] Add Zen Browser

### ISSUE THREAD

**Issue by botus99** [cosmic-utils/web-apps#53]
## Description:
When creating a new Web App, the 'Select Browser' option shows some of my Flatpak installed browsers (LibreWolf, Ungoogled Chromium, Floorp...), but not Zen Browser, which I also have installed through Flatpak.

## Steps to Reproduce:
1. Create new Web App
2. Attempt to select a browser other than the already working browsers (for me,  I can see LibreWolf, UC, Floorp...)
3. ???

## Expected Behavior:
Ability to select Zen Browser from the available web browsers

## Actual Behavior:
Ability to select the installed browsers mentioned above, but not Zen Browser

## Environment:
- **Operating System:** Debian Testing
- **WebApps Version:** v0.4.6

## Additional Context:
I am guessing this will be a simple copy/paste & find/replace fix from [issue #26](https://github.com/elevenhsoft/WebApps/issues/26)

Loving the app so far. Thank you very much for your hard work!

**Comment by elevenhsoft** [comment]
Hey,

I will check this out. I know only it's based on Firefox somehow, so should works in the same way. Not sure about it's UI since it's very customized i guess (?) and it can behave weird but simple support can be added.

Also, can it be installed via flatpak right? What about some .deb? I don't know if flatpak support is enough.

**Comment by elevenhsoft** [comment]
> Essentially, Zen is to Firefox what Arc is to Chrome. So yes, a _heavily_ customized fork. They got a big surge in popularity over the last couple weeks.
> 
> Zen can be installed with the following command for Flatpak...
> 
> ```
> flatpak install io.github.zen_browser.zen
> ```
> 
> Zen's latest release page doesn't appear to have a .deb release. It is still in alpha it seems, so there is a possibility that a .deb will happen eventually. Haven't checked to see if they're working on that yet, though.
> 
> Here is a link to their repo... [github.com/zen-browser/desktop](https://github.com/zen-browser/desktop)

Thank you!

I added this, so it's found in Web Apps: https://github.com/elevenhsoft/WebApps/commit/4f328f5fa57bc36aa49a2719a5a84976511e45e8

Unfortunately, since it's mostly customized with its interface, it's require much more work to hide for example navbar. It's not working with Firefox's custom css.

**Comment by botus99** [comment]
No problem!

Ah, that makes sense about the css. That actually isn't a big deal IMO. Zen has a Theme Store (their own browser extensions store) where there are ways to tweak the Navigation Bar. So, you should still be able to customize the Nav Bar within the created web app potentially. 

I'll report back if I can get my idea to work, in case anyone besides us are interested haha.

Thanks for the lightning quick response and action!

**Comment by elevenhsoft** [comment]
Ok, so it's possible to hide navbar. Not sure why it's not working out of the box, but require little tweak.

**Comment by elevenhsoft** [comment]
Nevermind, I guess I fixed it: https://github.com/elevenhsoft/WebApps/commit/4bffd6449b1fccc773ac9c7cc6560ad6a253ab97

**Comment by botus99** [comment]
@elevenhsoft, you're a madman. Don't ever change!

Can't wait to try this out. Your work is greatly appreciated!

**Comment by elevenhsoft** [comment]
Haha thank you ^^ unfortunately for flatpak release you need to wait, im not sure when i will release it since there are few stoppers :P

**Comment by botus99** [comment]
IIRC, it took a day or 2 the last time I made a feature request like this. I'll keep my eyes open for an update, but Flathub is Flathub. No worries there. :)

**Comment by elevenhsoft** [comment]
Its basically because recent updates of libcosmic. We need to provide also cosmic-icons in flatpak runtime. They said maybe will be something like Cosmic platform for flatpak which should simplify this process :)

**Comment by botus99** [comment]
Just got the update this morning. It is working more or less.

Disabling the Nav Bar is a little goofy, like you mentioned before. I get the feeling that Zen made some changes since we last talked that messed around with your fix... totally not sure, just a feeling haha.

Well, off to work for now. I'll play around with this later and see if I can find out anything useful.

Thanks again for the hard work!

**Comment by elevenhsoft** [comment]
Ah yeah. I forgot about testing Zen browser more. I'm not sure what's happening. Previously it worked somehow, but maybe some changes broke it :P

**Comment by elevenhsoft** [comment]
It should be fixed by: https://github.com/cosmic-utils/web-apps/pull/59
