### ISSUE TITLE
Selected icon but another one is used

### ISSUE THREAD

**Issue by mbridon** [cosmic-utils/web-apps#57]
Hi, I created a web app for https://ameli.fr, the site of the French national healthcare system.

I used the feature to download the icon.

Then I try to create a web app for https://www.impots.gouv.fr/accueil, the site of the French tax system, and try to download the icon, no icon is added. Ok, I guess the website doesn't declare its icons properly... :confused: 

So I selected an icon manually for it, but the icon for the ameli webapp is used. :confounded: 

It seems the first app icon gets reused for other web apps. :facepalm: 

![image](https://github.com/user-attachments/assets/8219efb0-9e18-4620-af64-d281b7f776d1)
![image](https://github.com/user-attachments/assets/a4c87c8f-dedf-4160-9c1b-4bf5aa654c8f)

**Comment by elevenhsoft** [comment]
Hello, Thanks for your report!

I will test it a bit and see if can reproduce. I guess it would be nice to clear inputs after successfully creating web app. It should solve this. I was writing this app long time ago when learning and there is many bugs probably here and there. I must revisit it with new ideas ^^

Anyway, today I will look into it:)

**Comment by mbridon** [comment]
The icon I chose for the "impôts" webapp is this one: 
![icone impots](https://github.com/user-attachments/assets/adab883c-535f-4857-8ba4-3aade92e23b1)

**Comment by elevenhsoft** [comment]
It's something messed with the icon selection logic. Would be nice to simplify this. I will try to do this today.

**Comment by elevenhsoft** [comment]
Btw. are you using flatpak of repo version?

**Comment by mbridon** [comment]
> Btw. are you using flatpak or repo version?

I'm using Flatpak,from Flathub, what else? :smirk:

**Comment by elevenhsoft** [comment]
Ok. Just curious. You probably will wait a bit for a fix. I'm working on rewriting this app, not huge changes but some cleanup etc. Maybe I will be able to sort out some bugs meanwhile. 
That's mean, until I push update for flathub it can take some time, but I will try to do my best ^^

**Comment by elevenhsoft** [comment]
This is fixed already in master. Waiting for some changes on flathub.

**Comment by mbridon** [comment]
Awesome, thank you 😊

**Comment by mbridon** [comment]
I can confirm that with version 0.5.0 this is now fixed. :tada:

**Comment by elevenhsoft** [comment]
Thank you! I hope I did not broke anything else ^^
