### ISSUE TITLE
Favicon are blurry

### ISSUE THREAD

**Issue by wiiznokes** [cosmic-utils/web-apps#62]
For YT music for example, the icon dowloaded is very much blurry. I think this could be improved, for example, this site https://favic.one/ is able to show a high quality icon of https://music.youtube.com

**Comment by elevenhsoft** [comment]
Current service has public API and fallback to duckduckgo and google if image is not found. Probably that's why it's blurry since favicons are basically small images. I don't know if it's worth to change provider. We also using papirus icons which have a lot of icons we can use. Favicons are just in case. Also, we can use custom images via file chooser.

**Comment by wiiznokes** [comment]
I will try to come up with something

**Comment by wiiznokes** [comment]
Ok, so the current way of fetching favicons seems nice (the downside being that it require a third party service).
I just realize that you can choose between all favicons downloaded. Unfortunately, the default one was the most blurry for yt music.

```
[src/pages/mod.rs:400:17] &result = [
    "https://music.youtube.com/favicon.ico",
    "https://music.youtube.com/img/favicon_32.png",
    "https://music.youtube.com/img/favicon_48.png",
    "https://music.youtube.com/img/favicon_96.png",
    "https://music.youtube.com/img/favicon_144.png",
]
```
I would suggest to sort by size and choose the one with the more pixel, or with a vector format.

**Comment by elevenhsoft** [comment]
> I would suggest to sort by size and choose the one with the more pixel, or with a vector format.

Yeah, in this case it should choose 96px and 144px sizes. Probably it's picking first one found? I'm not sure. Will look into it today. Thanks!

> Edit: favicon should also have the priority over the icons found of the filesystem.

Not bad idea.

**Comment by elevenhsoft** [comment]
I think this: https://github.com/cosmic-utils/web-apps/commit/0a727ff96363d25055a1a42a600a89ac74fe2c13 should fix this blurry icons. Now it should check each icon and use only with size above 96x96px. Also fixed bug when favicons were in svg so it was pushed as Raster handle and in result it was not displayed in the icon picker. Now the priority for favicons. That's a good idea :)
