### ISSUE TITLE
profile automatically logged out eveytime switch to diffrent window manager in the flatpak version

### ISSUE THREAD

**Issue by Partha996** [cosmic-utils/web-apps#68]
my web apps automatically logout when switching between kde and hyprland and if i again sign in in one Wm than switch to another it's again logged out , i use brave for the web apps

**Comment by elevenhsoft** [comment]
To be honest I'm not sure what causes it. Profile is stored on your home directory so it's not it.
I would assume, there is some issue with keyring. For example I remember I had this issue with Brave and other chromium browsers when using GNOME and GNOME keyring and some WM. The keyring was not unlocked what causes this issue.

**Comment by Partha996** [comment]
You're right, this keyring issue is the main problem. It only occurs in chromium-based browsers. I didn't even know what a keyring was, before using a chromium browser. I tried LibreWolf and Zen Browser, and they both work fine
